# SITE CONFIGURATION
url: "https://spff1.github.io"

author: spff1
title:  spff1.github.io
logo:   forest.svg
description: "Well, I'm learning"

excerpt_separator: "<!--more-->"

social:
  - icon:           rss
    url:            /feed.xml
    description:    RSS feed
  - icon:           github
    url:            https://github.com/
    description:    Github
  - icon:           envelope
    url:            mailto:nomail@nomail
    description:    Email

permalink: /:year/:month/:title/

paginate: 16
paginate_path: "page/:num"
post_navigation: true

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
